name: Deploy api to heroku on push to main

on:
  push:
    branches:
      - main

jobs:
  # deploy to netlify
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
    - uses: actions/checkout@v2

    # deploy to Heroku
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "aquinfo-api"
          heroku_email: "rafael.g.depaulo@gmail.com"
        branch: "master"
